### ISSUE TITLE
加入match之后list index out of range

### ISSUE THREAD

**Issue by EricAugust** [airaria/TextBrewer#10]
2020-05-15 11:58:57,166 - INFO - matches:['L3_hidden_mse', 'L3_hidden_smmd']
2020-05-15 11:58:57,177 - INFO - 加载字典
2020-05-15 11:58:57,241 - INFO - using device:cuda
2020-05-15 11:58:57,241 - INFO - 初始化BERT模型
2020-05-15 11:58:59,816 - INFO - 加载Teacher模型～
2020-05-15 11:59:03,855 - INFO - /home/user10000281/notespace/dialogue/model/bert.model.epoch.29 loaded!
2020-05-15 11:59:03,856 - INFO - 将模型发送到计算设备(GPU或CPU)
2020-05-15 11:59:03,948 - INFO - 加载Student模型～
2020-05-15 11:59:04,240 - INFO - /home/user10000281/notespace/dialogue/lib/bert/pytorch_model.bin loaded!
2020-05-15 11:59:04,249 - INFO - 将模型发送到计算设备(GPU或CPU)
2020-05-15 11:59:04,292 - INFO - 加载训练数据
2020-05-15 11:59:52,372 - INFO -  声明需要优化的参数
2020-05-15 11:59:52,373 - INFO - Length of all_trainable_params: 2
2020-05-15 11:59:52,389 - INFO - [{'layer_T': 0, 'layer_S': 0, 'feature': 'hidden', 'loss': 'hidden_mse', 'weight': 1}, {'layer_T': 4, 'layer_S': 1, 'feature': 'hidden', 'loss': 'hidden_mse', 'weight': 1}, {'layer_T': 8, 'layer_S': 2, 'feature': 'hidden', 'loss': 'hidden_mse', 'weight': 1}, {'layer_T': 12, 'layer_S': 3, 'feature': 'hidden', 'loss': 'hidden_mse', 'weight': 1}, {'layer_T': [0, 0], 'layer_S': [0, 0], 'feature': 'hidden', 'loss': 'mmd', 'weight': 1}, {'layer_T': [4, 4], 'layer_S': [1, 1], 'feature': 'hidden', 'loss': 'mmd', 'weight': 1}, {'layer_T': [8, 8], 'layer_S': [2, 2], 'feature': 'hidden', 'loss': 'mmd', 'weight': 1}, {'layer_T': [12, 12], 'layer_S': [3, 3], 'feature': 'hidden', 'loss': 'mmd', 'weight': 1}]
2020/05/15 11:59:53 - INFO - Distillation -  Training steps per epoch: 21234
2020/05/15 11:59:53 - INFO - Distillation -  Checkpoints(step): [0]
  0%|                                                                                                                                                                               | 0/50 [00:00<?, ?it/s]2020/05/15 11:59:53 - INFO - Distillation -  Epoch 1
2020/05/15 11:59:53 - INFO - Distillation -  Length of current epoch in forward batch: 21234
0it [00:00, ?it/s]
  0%|                                                                                                                                                                               | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_distil.py", line 239, in <module>
    main()
  File "train_distil.py", line 189, in main
    num_epochs=args.num_train_epochs, callback=callback_func)
  File "/home/user10000281/.local/lib/python3.6/site-packages/textbrewer/distillation.py", line 435, in train
    super(GeneralDistiller, self).train(optimizer, scheduler, dataloader, num_epochs, num_steps, callback, batch_postprocessor, **args)
  File "/home/user10000281/.local/lib/python3.6/site-packages/textbrewer/distillation.py", line 194, in train
    total_loss = self.train_on_batch(batch,args)
  File "/home/user10000281/.local/lib/python3.6/site-packages/textbrewer/distillation.py", line 505, in train_on_batch
    inter_S = inters_S[feature][layer_S]
IndexError: list index out of range
不知道为什么会出现这个问题

**Comment by airaria** [comment]
你可以检查以下几个关键点：
1. （教师/学生）模型是否返回了足够数量的hidden states？比如你这段代码里要求教师返回长度13的list（embedding  + 12 hidden states)，学生返回长度4的list (embedding + 3 hidden states);
如果你用的是HuggingFace的Transformers, 需要在对应模型的config里设置 config.output_hidden_states=True。见https://huggingface.co/transformers/model_doc/bert.html?highlight=output_hidden_states
2. adaptor里是否正确匹配了模型的输出并正确返回了dict ，其中 dict['hidden'] = 模型输出的hidden_states?

**Comment by MarvinLong** [comment]
> 你可以检查以下几个关键点：
> 
> 1. （教师/学生）模型是否返回了足够数量的hidden states？比如你这段代码里要求教师返回长度13的list（embedding  + 12 hidden states)，学生返回长度4的list (embedding + 3 hidden states);
>    如果你用的是HuggingFace的Transformers, 需要在对应模型的config里设置 config.output_hidden_states=True。见https://huggingface.co/transformers/model_doc/bert.html?highlight=output_hidden_states
> 2. adaptor里是否正确匹配了模型的输出并正确返回了dict ，其中 dict['hidden'] = 模型输出的hidden_states?

好像attention的还是对应不上，我的理解是attention的index-1，不知道这样对不对。
L4_attention_mse=[{"layer_T":3,  "layer_S":1, "feature":"attention", "loss":"attention_mse", "weight":1},
                  {"layer_T":6,  "layer_S":2, "feature":"attention", "loss":"attention_mse", "weight":1},
                  {"layer_T":9,  "layer_S":3, "feature":"attention", "loss":"attention_mse", "weight":1},
                  {"layer_T":12, "layer_S":4, "feature":"attention", "loss":"attention_mse", "weight":1}]

**Comment by airaria** [comment]
你返回的attention list 是包含13个元素吗？原版的transformer里attention的长度只有12。你可能需要将index-1:
L4_attention_mse=[{"layer_T":2, "layer_S":0, "feature":"attention", "loss":"attention_mse", "weight":1},
{"layer_T":5, "layer_S":1, "feature":"attention", "loss":"attention_mse", "weight":1},
{"layer_T":8, "layer_S":2, "feature":"attention", "loss":"attention_mse", "weight":1},
{"layer_T":11, "layer_S":3, "feature":"attention", "loss":"attention_mse", "weight":1}]

**Comment by MarvinLong** [comment]
> 你返回的attention list 是包含13个元素吗？原版的transformer里attention的长度只有12。你可能需要将index-1:
> L4_attention_mse=[{"layer_T":2, "layer_S":0, "feature":"attention", "loss":"attention_mse", "weight":1},
> {"layer_T":5, "layer_S":1, "feature":"attention", "loss":"attention_mse", "weight":1},
> {"layer_T":8, "layer_S":2, "feature":"attention", "loss":"attention_mse", "weight":1},
> {"layer_T":11, "layer_S":3, "feature":"attention", "loss":"attention_mse", "weight":1}]

是的确实要减一，matches.py文件中的attention老师和学生的对应index都减一，使用attention进行蒸馏就没问题了。
