### ISSUE TITLE
interpreting intermediate matches

### ISSUE THREAD

**Issue by kaliaanup** [airaria/TextBrewer#103]
Can you please provide more insights into how to construct intermediate matches for a smaller model? For example for T3, T3-small and BiGRU. Somehow this is not clearly stated in the paper nor in the documents

![Screen Shot 2022-06-09 at 11 09 41 AM](https://user-images.githubusercontent.com/8302569/172881131-f2361435-b3e6-48de-960f-927d6e901858.png)

**Comment by kaliaanup** [comment]
Thank you so much for the detailed explanation. If you can add these to your docs it will be super useful.

I am following up on the conll2003 example. I changed the distill_config as the following.

```python
distill_config = DistillationConfig(
            temperature = 8,
              # intermediate_matches = [{'layer_T':10, 'layer_S':3, 'feature':'hidden','loss': 'hidden_mse', 'weight' : 1}]
              intermediate_matches = [
            {'layer_T':0,  'layer_S':0, 'feature':'hidden','loss': 'hidden_mse', 'weight' : 1,'proj':['linear',384,768]},
            {'layer_T':4,  'layer_S':1, 'feature':'hidden','loss': 'hidden_mse', 'weight' : 1,'proj':['linear',384,768]},
            {'layer_T':8,  'layer_S':2, 'feature':'hidden','loss': 'hidden_mse', 'weight' : 1,'proj':['linear',384,768]},
            {'layer_T':12, 'layer_S':3, 'feature':'hidden','loss': 'hidden_mse', 'weight' : 1,'proj':['linear',384,768]}]
            )
```

The run_conll2003_distill_T3.sh file looks as the following.

```sh
export OUTPUT_DIR="resource/taggers/T3-small-bert-finetuned"
export BATCH_SIZE=32
export NUM_EPOCHS=3
export SAVE_STEPS=750
export SEED=42
export MAX_LENGTH=128
export BERT_MODEL_TEACHER="resource/taggers/bert-finetuned"
python run_ner_distill.py \
--data_dir english_dataset \
--model_type bert \
--labels label_prod.txt \
--model_name_or_path $BERT_MODEL_TEACHER \
--output_dir $OUTPUT_DIR \
--max_seq_length  $MAX_LENGTH \
--num_train_epochs $NUM_EPOCHS \
--per_gpu_train_batch_size $BATCH_SIZE \
--num_hidden_layers 3 \
--save_steps $SAVE_STEPS \
--learning_rate 1e-4 \
--warmup_steps 0.1 \
--seed $SEED \
--do_distill \
--do_train \
--do_eval \
--do_predict
```

I am getting an index out of range error. Can you please check?

Traceback (most recent call last):
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/run_ner_distill.py", line 531, in <module>
    main()
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/run_ner_distill.py", line 460, in main
    train(args, train_dataset,model_T, model, tokenizer, labels, pad_token_label_id,predict_callback)
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/run_ner_distill.py", line 147, in train
    distiller.train(optimizer,train_dataloader,args.num_train_epochs,
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/textbrewer/distiller_basic.py", line 283, in train
    self.train_with_num_epochs(optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_epochs, callback, batch_postprocessor, **args)
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/textbrewer/distiller_basic.py", line 212, in train_with_num_epochs
    total_loss, losses_dict = self.train_on_batch(batch,args)
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/textbrewer/distiller_general.py", line 79, in train_on_batch
    total_loss, losses_dict = self.compute_loss(results_S, results_T)
  File "/Users/akalia/Research_Projects/NER-EL-Evaluation/textbrewer_ner_distiller/textbrewer/distiller_general.py", line 143, in compute_loss
    inter_S = inters_S[feature][layer_S]
IndexError: list index out of range

**Comment by airaria** [comment]
Did you set the model to return hidden states by `model.config.output_hidden_states=True` (if you distilled with hidden states)?

If it is still not working, would you please print the length of the  `inters_S[feature]`  and `inters_T[feature]`by inserting inters_S[feature] and  inters_T[feature]` to the line 140 of `textbrewer/distiller_general.py`?
